### ISSUE TITLE
Updates regarding PhET-iO and state

### ISSUE THREAD

**Issue by samreid** [phetsims/mean-share-and-balance#100]
During https://github.com/phetsims/axon/issues/409 I noticed some PhET-iO state parts that needed to be updated.  I'll commit the changes then request review from @marlitas.

**Comment by samreid** [comment]
Fixed, @marlitas can you please review?

**Comment by marlitas** [comment]
The only thing I noticed is that you removed `phetioReadonly: true` from `MeanProperty`. I don't think that should change. It would be strange if clients are able to change the value of MeanProperty since it's a calculation based on the content of the 3D cups. I don't think we should allow those to get separated.

**Comment by samreid** [comment]
I observed that DerivedProperty defaults to `phetioReadonly: true` so I thought it did not need to be repeated in the subtype.  Maybe we should even remove phetioReadonly from the DerivedProperty options?  I'm not sure about that.

**Comment by marlitas** [comment]
Ahhh okay. Yes I see. If setting `phetioReadonly: false` does actually allow clients to change the value then that seems okay, however if specifying that option doesn't do anything then does does feel rather confusing and mischievous. I'll revert that previous commit and close.
