### ISSUE TITLE
It looks odd when closing pipes

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/mean-share-and-balance#113]
**Test device**
MacBook Air m1 chip

**Operating System**
macOS 12.5.1

**Browser**
safari 15.6.1

**Problem description**
For https://github.com/phetsims/qa/issues/835:
 When I toggle the pipes closed, the water levels in the 2D cups immediately sync with the levels in the 3D cups, but the valve is still slowly turning. Is there a way for these two actions to match up better?

**Visuals**

https://user-images.githubusercontent.com/87318828/191081579-3a792523-dd9f-47eb-bf2e-ba273bff6cba.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Mean: Share and Balance‬
URL: https://phet-dev.colorado.edu/html/mean-share-and-balance/1.0.0-dev.8/phet/mean-share-and-balance_all_phet.html
Version: 1.0.0-dev.8 2022-09-16 20:09:53 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Safari/605.1.15
Language: en-US
Window: 1324x717
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by marlitas** [comment]
I pushed a commit that adds animation to the water levels when pipes close. This seems to match better. 

However, I noticed the water levels still snap with `reset-all` but the pipes are animating to a closed position. I'm assuming we would want this to match as well, but I wasn't sure if we want both the pipes and water levels to snap to their original positions during reset all, or if we want it to animate. 

My feeling was that reset-all feels like a more immediate sim response rather than an in time physical action.  

> I tried adding a video to show the current `reset-all` behavior but Github is currently not allowing me to.

@amanda-phet what are your thoughts here? It is rather simple to change the behavior either way.

**Comment by amanda-phet** [comment]
Discussed 10/17/22 and we decided to not have animations on reset-all, so the valves just snap back into place in that case. 

As for the animation issue, I am OK with the pipe connectors not changing color in a realistic way, and like the animation @marlitas added when animating to a closed position.

**Comment by marlitas** [comment]
These changes were added in and is ready to send back to QA. @amanda-phet tagging you also in case you want to confirm that this is behaving as expected. 

@Nancy-Salpepi how is this looking on your end with the changes and concerns addressed above?

**Comment by Nancy-Salpepi** [comment]
I love the animation to the water levels when closing the pipes @marlitas! 
The pipes now snap back into place on Reset All. Looks good! 🙂

**Comment by marlitas** [comment]
Great. Thanks for checking it out! I'm going to close this as completed.
