### ISSUE TITLE
PhET-iO naming for the different representations

### ISSUE THREAD

**Issue by samreid** [phetsims/mean-share-and-balance#119]
We need to decide on the phet-io naming for the different representations in each screen.  We currently have:

* (screen 1) Water cup 3d -> water cup 2d
* (screen 2) Person -> Plate Chocolate (should at least be changed to paperChocolate).

@marlitas and I will take a first look, then ask for feedback from @amanda-phet and @kathy-phet

**Comment by kathy-phet** [comment]
Could take on an original / raw / initial data vs analyzed data naming convention. 
e.g. waterCupsInitialData vs waterCupsAnalyzedData (don't love it, but do favor this kind of naming over something visually specific)

**Comment by kathy-phet** [comment]
What about raw data? 

chocolateBarRawData
chocolateBarAnalyzedData

**Comment by kathy-phet** [comment]
I like starting with the word chocolateBar or cookies ... because then they are proximate and connected better in the studio tree.

**Comment by marlitas** [comment]
My concern with relying on chocolateBar or Cookies is that it's difficult to distinguish if we're talking about the chocolate bar stack or the individual chocolate bar in a stack. We could perhaps say `chocolateBarStackRawData`... does that work for cookies too? 

But then is that inconsistent with the first screen? The container here is the cup so we are referencing the container `cupRawData` instead of the container's contents ( `waterRawData` ).

@samreid mentioned that it might be best to also sketch out the full tandem tree so that the tandems are contextualized. 

Leaving self-assigned to identify the existing tandems and trying out some of the proposals in context.

**Comment by marlitas** [comment]
Here is a sketched out tandem tree for the first three screens for some of the proposals from above. I tried to combine them as best I could.

I did run into a quirk with Fair Share. I had been differentiating chocolate stacks and bars with `chocolateStackRawData` and `chocolateBarRawData`, however `cookieBarRawData` sounds weird... so perhaps just `cookieRawData`? I'm not sure. But this should at least give us a starting point to adjust from. 

mini tandem tree:
- introScreen =>
  - model =>
    - cupRawData =>
      - waterLevelProperty
    - cupAnalyzedData =>
      - waterLevelProperty
    - pipeAnalyzedData
  - view =>
    - cupRawData =>
      - waterLevelSlider
    - cupAnalyzedData =>
      - tickMarks
    - pipeAnalyzedData =>
      - valveRotationFireListener

- levelingOutScreen =>
  - model =>
    - chocolateStackRawData =>
      - chocolateNumberProperty
    - chocolateStackAnalyzedData
    - chocolateBarAnalyzedData =>
      - parentPlateProperty
  - view =>
    - chocolateStackRawData =>
      - numberPicker
    - chocolateStackAnalyzedData
    - chocolateBarAnalyzedData =>
      - chocolateBarDragListener

- fairShareScreen =>
    - model =>
        - cookieStackRawData =>
            - cookieNumberProperty
        - cookieStackAnalyzedData
        - cookieBarAnalyzedData / cookieAnalyzedData =>
            - parentPlateProperty
    - view =>
        - cookieStackRawData =>
            - numberPicker
        - cookieStackAnalyzedData
        - cookieBarAnalyzedData / cookieAnalyzedData =>
            - cookieDragListener

**Comment by samreid** [comment]
@marlitas and I considered this renaming:

<img width="367" alt="image" src="https://user-images.githubusercontent.com/679486/196754305-2c1f0d9d-60d2-42c7-ac04-fafb037bdac6.png">

**Comment by samreid** [comment]
We kind of liked this:

<img width="310" alt="image" src="https://user-images.githubusercontent.com/679486/196755271-e8089afb-dd3e-4f9b-8d03-62cdb1a584da.png">

**Comment by marlitas** [comment]
Wanted to put eyes back on this for @kathy-phet and @amanda-phet. I feel ready to convert tandem names based on the recommendation in https://github.com/phetsims/mean-share-and-balance/issues/119#issuecomment-1284310974. How does this feel? It would be good to settle on a naming convention before we start the "Fair Share" screen.

**Comment by kathy-phet** [comment]
I like the naming convention for cups. 

So what would the other screens be? 
cookiePlate1
cookieSketch1

chocolatePlate1
chocolateSketch1

or 
plate1
plateSketch1

if its just plate then screen 2 and 3 will have the same naming convention.

**Comment by marlitas** [comment]
I think going the plate1 / plateSketch1 route would be best. Here's a screenshot of what that could look like in the Leveling Out screen. 
<img width="369" alt="Screen Shot 2022-10-27 at 8 51 22 PM" src="https://user-images.githubusercontent.com/42476338/198485936-4c3c9425-8195-485e-b2a4-17a1d85eca63.png">

**Comment by marlitas** [comment]
We need to revisit this conversation early on as development for MSaB begins again. It's going to be important so that we don't have to deal with constant renames moving forward. Pinging @amanda-phet to put it on her radar.

**Comment by jbphet** [comment]
@amanda-phet, @marlitas, and I just discussed this, and we are currently thinking we'll use the following:
- cups & cupSketches for the 1st screen
- plates & plateSketches for screens 2 and 3
- Things that appear in the notepad are "sketches", so we would use 'candyBarSketches' for the collection and 'candyBarSketchN' for the individual elements on the 2nd screen, 'cookieSketches' for the collection and 'cookieSketchN' on the 3rd screen.
- On the 4th screen, we will use 'soccerBallN' for the ones at the bottom.  The balls shown in the notepad are not interactive in this screen, so it's a little different, and we haven't yet decided whether to call them 'soccerBallSketches' or something different.  We'll leave this as an open question for now.  We're also still thinking about what to call the fulcrum.

**Comment by marlitas** [comment]
I'll handle this

**Comment by marlitas** [comment]
I started working on this and ran into some confusing situations in the code. @jbphet and I then talked and he agreed that it was confusing and warranted a revisit of the conversation.

In the code the 3DCups and the 2DCups have the same Cup model. This made it incredibly confusing when we then started renaming things in the `IntroModel` to `cupArray` and `cupSketchArray` even though they're both made up of `Cup` models. There is no reason to give the two representations their own custom model, the difference is only in how the cups are rendered.

In addition there are spots where we are only grabbing from the `cupArray`, which is then abstracted out and a quick glance through the code has no way to tell us which type of cup representation we're working with. It's very confusing. 

This will affect us a bit, but not as much with `plate` and `plateSketch`. In LevelingOut and FairShare at least `plate` and `plateSketch` have their own respective models, so it will be easier to distinguish things through typescript.

We believe that we need to rethink the `cup` vs. `cupSketch` rename. There needs to be a way to indicate where each representation is coming from so that it is easier to follow in the code.

Flagging this for another discussion.

**Comment by marlitas** [comment]
Meeting from 1/19/24

- @jbphet recommended doing `tableCupN`/ `tableCups` and `notepadCupN`/ `notepadCups`
  - We liked this, and felt that maybe we were trying to overEngineer the term
 - LevelingOut would only have `notepadCandyBar` and then each representation of a plate would be either:`tablePlate` or `notepadPlate`
 - BalancePoint would be: `soccerBalls` and `notepadDataPoints`

We all agreed to move forward with the above.

**Comment by marlitas** [comment]
This was done above. Over to @jbphet for code review and @amanda-phet for phet-io studio tree review

**Comment by amanda-phet** [comment]
It all seems clear enough to me, but I'm wondering if `meanShareAndBalance.levelingOutScreen.model.plate1` should be `meanShareAndBalance.levelingOutScreen.model.tablePlate1`since it's really about the tablePlate? I think either way is fine, but it seems like `meanShareAndBalance.levelingOutScreen.model.notepadCandyBars.notepadCandyBar1.parentPlateProperty` would be easier if it was giving the value as `tablePlate1` instead of `plate1`. If I'm wrong about this, then please ignore me and keep going with naming as it is!

**Comment by jbphet** [comment]
@amanda-phet - Due to some recent changes in the code, there is now only one instance of the `Plate` type for each position at the table.  This plate has a Property that represents the number of candy bars on the table version of the plate (which is now also used to show the dotted outlines that can appear on the notepad version of the plate), and also can be referenced by the notepad candy bars to represent which ones are stacked on it in the notepad view.  So, as far as the code is now concerned, it really *is* just a single plate with two views, one at the table and one in the notepad.  

I realize that this may potentially be confusing to educational designers and other potential users of phet-io, so please give it a bit of thought and let us know if you think this needs to be structured differently - specifically, should there be separate model elements for the table plates and the notepad plates instead of different views of the *same* model element.  One of the downsides of having them separate is that the code would need to prevent them from getting out of sync via the phet-io API.  And it's just more code.  The main upside is that having them separate may be easier for customers to get their heads around.

**Comment by amanda-phet** [comment]
I believe the naming for these things is all sorted out now! notepadCups, tableCups, notepadPlates, and tablePlates, are all working well. Closing.
