### ISSUE TITLE
Use GroupSortInteraction for this sim

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#137]
Refer to https://github.com/phetsims/soccer-common/issues/2 for more details. The work in https://github.com/phetsims/scenery-phet/issues/815 will need to start before or with MSaB development. 

This issue is a high-priority for MSaB, and is therefore blocking this sim's publication.

**Comment by zepumph** [comment]
We discussed this during a meeting with @marlitas @jessegreenberg and I today. We found that likely the current implementation for CAV soccer balls would work pretty well for the case in MSaB. That said, it is still worth an abstraction because it may apply elsewhere, like for rearranging chocolate bars on the second screen. We will do some exploration over in https://github.com/phetsims/scenery-phet/issues/815 and report back.

**Comment by jbphet** [comment]
@marlitas and I just discussed this with @zepumph and the current understanding is that the interaction handler, which is called `GroupSortInteraction`, is in good shape for the soccer ball case in Center & Variability, and the next step is to try to apply it to the candy bar case on the 2nd screen.

At the time of this writing, `GroupSortInteraction` is not yet ready for @marlitas and I to try to use it for the candy bars.  We should wait until we get the word from @zepumph that it's ready for integration, which he is estimating will be this coming Friday.

**Comment by zepumph** [comment]
There is still one minor item that I am working on with GroupSortInteraction in regards to how interactive highlights + keyboard interaction can play together, but that is minor, and is making good progress. I feel very good about the MSaB team starting to use GroupSortInteraction now. Thanks for your patience and let me know how it goes.

**Comment by zepumph** [comment]
Also noting that a general code review issue can be found at https://github.com/phetsims/scenery-phet/issues/841.

**Comment by marlitas** [comment]
Starting on this! Will add any questions or feedback in this issue. Thanks!

**Comment by marlitas** [comment]
Group sort has been added to this sim, and I believe it's implementation is ready for review. There are a few questions I have about cues matching across screens, but I think those are design polishes that do not need to be mixed into this issue. Over to @jbphet for review. If all looks well this can be closed.

**Comment by jbphet** [comment]
Generally I'd say that the code for this looks good - reasonably structured and decently commented.  Having said that, my experience with group sort interaction is basically nil, so I can't comment much on whether it's being used as intended.

The one thing I did notice that prevents me from closing the issue is that there is a TODO for this issue in what is now `DistributeModel` which says, "Does this now need to extend PhetioObject to work with GroupSortInteractionModel?".  I think the answer must be "no" or it wouldn't work, but I thought I'd send this back to @marlitas to confirm and to remove the TODO if it is safe to do so.  After that, this should be good to close.

**Comment by marlitas** [comment]
I removed the TODO in a different issue. Thanks for looking it over @jbphet! I think we're ready to close.
