### ISSUE TITLE
A few open questions about GroupSortInteraction

### ISSUE THREAD

**Issue by zepumph** [phetsims/mean-share-and-balance#141]
While discussing https://github.com/phetsims/scenery-phet/issues/815, @marlitas @jbphet and I have some outstanding questions that will be best solved when @marlitas and @jbphet go to use this interaction in MSaB. I'll link todos to this issue.

**Comment by marlitas** [comment]
>   // TODO: MS and JB! Does this make sense to live inside of GroupSortInteractionModel? https://github.com/phetsims/mean-share-and-balance/issues/141
  //       Questions:
  //                  1. Do we wish this was a DerivedProperty somehow? (MK thinks probably not)
  //                  2. We need to update this value based on sim logic AND hard coded group sort logic (like mouseSortCueShouldBeVisible())
  //                  3. We need to manually call registerUpdateSortCueNode() in addition to any other spots that update the mouse sort cue.
  //                  4. Noting here that we don't have any code in group sort about creating the mouse cue Node itself (just the visibleProperty and if it should be shown from our perspective)

Over all question answer: yes. It makes sense to live here since it's so intertwined with the keyboard behavior. Did not cause any problems for me.

1. No. That does not seem necessary to me.
2. Is this question asking if we need an additional function on top of `mouseSortCueShouldBeVisible()`? If so, no. I think that is enough.
3. I think manually calling registerUpdateSortCueNode seems fine. Especially since it's directly mentioned in the Implementation Steps documentation.
4. That's fine. I think sim can handle creation and just hook into this Property for visibility.


> TODO: add this.enabledProperty into this like is done for soccer-common? https://github.com/phetsims/mean-share-and-balance/issues/141

Adding enabledProperty into `mouseSortCueShouldBeVisible` seems reasonable to me, especially if that's a Property that is being instrumented for PhET-iO. I'll look into doing that work.

**Comment by marlitas** [comment]
All the TODOs for this issue were handled and confirmed with @zepumph. Ready to close!
