### ISSUE TITLE
Water level behavior when removing a cup

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#17]
<img width="650" alt="Screen Shot 2022-05-17 at 1 28 10 PM" src="https://user-images.githubusercontent.com/42476338/168894428-f52afdfa-4688-40e6-bc5b-661d21f8c98d.png">
The 3D cup on the far right, has significantly more water than its corresponding 2D cup. Therefore, when it is removed by clicking the number spinner the amount of water we are removing in the 2D cups does not match the amount of water we are removing in the 3D cup.

It was straightforward to let that discrepancy animate, but we are curious if that might be confusing for students. We wanted to run this past @amanda-phet, before continuing further. What do you recommend? Would you like to see a version without the animation?

**Comment by amanda-phet** [comment]
Just to revisit this- We didn't discuss this situation when coming up with the design pattern for adding/removing cups after some sharing has occurred. However, it seems like removing the cup should "auto-borrow" from the other cups so that the total in the 2D accurately reflects the total water in the 3D cups. 

I think we can auto-borrow from the two 2D cups in this case. 

But what about a case like this? 

![image](https://user-images.githubusercontent.com/7852916/171279844-98b5a5aa-4986-4887-9697-ce056e5d808e.png)


It seems like auto-borrowing only from the 6th cup would make sense, but that breaks our rule of not keeping track of where water was shared/borrowed.

**Comment by amanda-phet** [comment]
Right now, if I remove the last cup and the water level doesn't match the 2D cup, the sim matches the 2D water levels to the 3D water levels. If valves are open, things level. If not, things don't. This feels pretty reasonable to me. We discussed some alternatives and those did not seem reasonable (auto-borrowing, auto-sharing, or needing to sync before removing a cup). I'll close this since this issue seems resolved!
