### ISSUE TITLE
Consider a refactor to simplify code in the "Leveling Out" and "Fair Share" screens

### ISSUE THREAD

**Issue by jbphet** [phetsims/mean-share-and-balance#185]
@marlitas and I have been talking about refactoring the code in screens 2 & 3 to make it simpler, more maintainable, and more amenable to phet-io.  I've spent some time thinking about this, and I think the main things we should try (at least initially) are:
- Have the plates keep track of the snacks (e.g. candy bars or apples) that are on them, rather than the current setup where the snacks keep track of the plate that they are one.
- Have snacks that are not in use be in a separate array so that they can be easily moved to a plate, or removed from one.  In the current design, snacks are always on plates and are stacked such that the active ones are on the bottom and the inactive (which are invisible) are on the top.  This leads to a need to re-stack them and swap them between plates in a number of cases, which seems unnecessarily complex.

I feel like these two changes could take the onus off of the model for continuously having to reconcile positions, stacking order, and snack-plate relationships, and thus make initialization, reset, and conveyance of state for phet-io easier.

@marlitas and I are thinking that we should attempt this on a branch so as not to destabilize the main branch while we try this out, since there is currently a dev version out for interviews that could potentially need some tweaks or fixes.

This issue is meant to be the place where we first discuss this and, once we feel like we have a plan, track the changes against.

**Comment by marlitas** [comment]
A couple of questions I want to make sure we have answered before moving forward on this...

- How will we track the state of what snacks are on what plate in PhET-iO? Currently we are doing this through a Property that tracks the parent plate. We can probably do this through an Observable Array which supports PhET-iO, but let's confirm.
- How will GroupSortInteraction know where to move or select candy bars? Currently the API for GroupSortInteraction requires the object being sorted to have a way to return a number for which "value" or "plate" in our specific case the object should move to. Currently this is done through the parentPlateProperty which returns it's index in the array of plates as the candyBar's value. For soccer balls this is done with it's number line value. By removing the parentPlateProperty we need to have another way that GroupSort can identify the candyBar's plate value, and also write to that value as it's being sorted. I am not quite sure how we would do this with ObservableArrays quite yet...

Other thoughts:
- Dragging/Animating: There was one point where we discussed that if a snack is animating or dragging it should not belong to a plate. Thinking through PhET-iO state this concerns me a bit. I believe we still need to make sure that a snack always knows if it is attached to a plate, otherwise we have no way to match the downstream state to the upstream. The ObservableArray is the only data that can give us that information. Especially in Leveling Out where candy bars can be moved to any plate regardless of what the "table" data is telling us.

**Comment by jbphet** [comment]
@marlitas discussed her questions above in a meeting this morning, and she and I are feeling like we should go ahead and move forward with this refactor, but as noted above, on a branch in case it doesn't work out.

**Comment by jbphet** [comment]
I wanted to get some metrics before doing any work on this to help us determine whether the refactor is truly beneficial.  I did some searching and ended up installing a command-line utility called `cloc`, which I think is short for "count lines of code".  I installed it from npm using the command `npm install -g cloc`, and then set up a file list with the file names that I think are most likely to be changed.  The list looked like this:

```
js/common/model/SharingModel.ts
js/common/model/Plate.ts
js/common/model/Snack.ts
js/leveling-out/model/LevelingOutModel.ts
js/leveling-out/leveling-out/CandyBar.ts
js/fair-share/model/FairShareModel.ts
js/fair-share/fair-share/Apple.ts
```

The invocation command was `cloc --by-file --md --list-file /c/temp/file-list.txt`, where `file-list.txt` contained the list of files shown above.  The `md` option is for markdown output, and it's very cool that `cloc` supports this.  Below is the table that it produced.  This is prior to any refactoring.

File|blank|comment|code
:-------|-------:|-------:|-------:
js/fair-share/model/FairShareModel.ts|103|100|429
js/leveling-out/model/LevelingOutModel.ts|54|87|219
js/common/model/SharingModel.ts|36|32|140
js/common/model/Snack.ts|36|37|92
js/common/model/Plate.ts|25|20|53
js/leveling-out/model/CandyBar.ts|13|15|33
js/fair-share/model/Apple.ts|9|9|24
--------|--------|--------|--------
SUM:|276|300|990

I'd love to also see if I could find some sort of code complexity metric to use, but it doesn't seem worth the time right now, so I'm going to go with the information above as a benchmark to help decide if the refactor is worthwhile.

**Comment by jbphet** [comment]
This is complete, and has been integrated into main.  Closing.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.

**Comment by marlitas** [comment]
Removed TODO. It was already addressed in another issue.
