### ISSUE TITLE
Clean up Dynamic Locale layouts

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#189]
Dynamic Locale is supported for all screens. This issue will confirm dynamic locale across all screens to make sure it is ready for design review.

**Comment by marlitas** [comment]
This is now ready for design review. @amanda-phet feel free to close if all looks well.

**Comment by amanda-phet** [comment]
Long strings sometimes make the checkboxes and spinners move up/down, which is odd. Since I'm testing using `stringTest=dynamic` then it's probably a scenario where a user wouldn't know they are moving, but I am still wondering why things are moving up/down when a string length is left/right. 

The accordion boxes are right-aligned, and a long title make the box quite a bit wider, shifting other things to the left, which I wouldn't want. But, we are removing the accordion boxes so this is no longer an issue. 

Assuming the first thing I brought up is expected, I'll go ahead and close!
