### ISSUE TITLE
Long String Layout

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#19]
When testing with long strings the current layout feels as if there is too much margin on the right. 
<img width="1500" alt="Screen Shot 2022-05-23 at 9 20 12 AM" src="https://user-images.githubusercontent.com/42476338/169852745-2abb0593-4367-4d2f-b55c-7061f99cc7d8.png">

However, if we decrease the margin, the controls feel crowded in English. 
<img width="1500" alt="Screen Shot 2022-05-23 at 9 20 35 AM" src="https://user-images.githubusercontent.com/42476338/169852784-014d9fc3-a1fa-44f3-80a7-3fa825bf9988.png">

@samreid suggested that it is possible that we could dynamically adjust the margin, however it is more complicated and we do not normally adjust layouts that way. If this is a special case we can do it though. 

Phettest should show the proposed wider margin that does not crowd in English if you want to compare to the narrower (in our opinion crowded) margin. Please clear cache to see accurate portrayal. You can also use the query parameter ( stringTest=long ), to see what longer text in the sim will look like.

**Comment by marlitas** [comment]
Meeting 6/1/22:
Decided to change the NumberPicker to a NumberSpinner, and place it above reset-all button.

**Comment by marlitas** [comment]
Layout adjusted to accommodate meeting decisions and lang strings. Assigning to @amanda-phet for review on checkbox and number spinner placement. Check with `stringTest=long`

**Comment by amanda-phet** [comment]
This is looking good to me! However at some point as strings get longer, the left edge here loses its alignment:
![image](https://user-images.githubusercontent.com/7852916/172473410-018c31bc-8398-4988-b48e-01a1d7c133f7.png)


![image](https://user-images.githubusercontent.com/7852916/172473464-e615b850-d6f7-408d-8b31-93fdb773e477.png)


Do you know what's going on? It seems like it happens when the string width maxes out, and the checkboxes seem to shift to the left. But the number spinner and Number of Cups text stay in their spot.

**Comment by marlitas** [comment]
@amanda-phet Not sure. I will check this out today and see if I can fix by our meeting tomorrow.

**Comment by marlitas** [comment]
Fixed and approved in design meeting. Closing.
