### ISSUE TITLE
Balance Point Screen Traversal Order

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#194]
This issue will track commits and design requests related to the traversal order for the Balance Point Screen.

**Comment by marlitas** [comment]
I believe this is ready for design review. Over to @amanda-phet.

**Comment by amanda-phet** [comment]
I think the order should probably go like this to be consistent with previous screens: 

**Play area**
1. kick button
2. fulcrum
3. check button
4. ball play area (maybe this could still come right after the kick button, not sure) 
5. ball spinner (this goes last in the "play area" on previous screens, and it's odd on this screen since the kick button does the same thing, but it should still be last) 

**Control panel**
scene selection
checkboxes
info button
reset all

**Comment by amanda-phet** [comment]
This looks great, thanks!
