### ISSUE TITLE
Changes to second screen (Leveling Out / Distribute) 

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/mean-share-and-balance#199]
- [x] Remove the mean accordion box and put the info button in that space
- [x] Update the info dialog to show the mean as a whole number plus a remainder
- [x] Remove the outlines on the notepad showing where a candy bar was moved
- [x] Add a cue to move the candy bars (yellow arrows similar to fulcrum) 
- [x] Set the initial values of people to be as follows: 3, 1, 5, 3, 8, 10, 5
- [x] Add a "predict mean" tool/checkbox
- [x] Add "success" cues to match the first screen (thresholds may need to be larger since these are discrete objects)
- [x] Add a "Total" checkbox that displays the total on the notepad
- [x] Move total back to the center of the notepad 
- [x] Make the 'sync' button inactive/disabled until a bar has been moved to a new stack 

![image](https://github.com/phetsims/mean-share-and-balance/assets/7852916/0f25e3e3-6e3e-42cc-81fe-546c82e88103)

![image](https://github.com/phetsims/mean-share-and-balance/assets/7852916/3a0b913b-90e6-41a4-907d-c435f9f4578b)

![image](https://github.com/phetsims/mean-share-and-balance/assets/7852916/655c4493-f374-453d-b181-fc3896a0940e)

**Comment by marlitas** [comment]
Everything has been addressed here. Over to @amanda-phet for design review and @jbphet for code review.

**Comment by amanda-phet** [comment]
Everything looks good! Thanks!

**Comment by jbphet** [comment]
A few comments:
- [ ] There should probably be an assertion to verify that the length of the `initialPlateValues` option is.  I would have just added it, but wanted to make sure you didn't want a default value if the length is shorter than the number of plates in the model.
- [ ] There is a TODO for this issue in `Plate.ts` that says, "Why can't I get the height from the Image below?".  First, I think we generally can't get image info at load time because the images aren't themselves loaded yet.  Second, I don't think we should use the image to define a model parameter.  I'd suggest removing `PLATE_HEIGHT` here and calculating it from an image in the constructor in `DistributeScreenView`, which appears to be the only place `PLATE_HEIGHT` is being used.
- [ ] I'm thinking that we should move the sound generation for predicting the mean into the `PredictMeanSlider` now that it is being reused and we have duplicated code for creating and adding this sound generator.  If you agree, please log an issue and feel free to assign it to me.
- [ ] I made minor doc and style changes and removed some unused code in a commit above.  Please have a quick look and make sure you're good with what was done.

**Comment by marlitas** [comment]
I agree with and applied changes to address feedback. Thanks for the review @jbphet!
