### ISSUE TITLE
Fair Share Screen: Sync/Collect/Share button styling 

### ISSUE THREAD

**Issue by emily-phet** [phetsims/mean-share-and-balance#210]
The Sync/Collect/Share buttons seem appropriately implemented as radio buttons, but the styling--where unselected radio buttons are greyed out--may be confusing to learners. They may appear unavailable. 

Suggestion: maintain the same "active" blue coloring for all, but add a bolder highlight around the activated button. 

I brought this up in today's meeting, other's also had the same feeling about the radio buttons, and suggested I make this issue. 
Handing over to @amanda-phet to consider.

**Comment by amanda-phet** [comment]
I didn't see any concerns in interviews (in fact these buttons worked seamlessly in all three). I'm open to redesigning the style of these buttons, but we generally use this paradigm everywhere we use this style of radio button so I hesitate to do something special in this sim. I will add this to the agenda for the next designers meeting.

**Comment by amanda-phet** [comment]
I lost my summary, I apologize. 

We discuss this issue and since this is rectangularRadioButtonGroup and it touches many many sims, we don't want to change that component. However, upon seeing the implementation across sims, we would like the default styling for rectangularRadioButtonGroup to have a bigger stroke on the selected button, rather than a customization.
