### ISSUE TITLE
Pencil leaves notepad area

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#223]
While doing some testing for https://github.com/phetsims/mean-share-and-balance/issues/221, I noticed that the pencil goes outside of the notepad area in the first two screens. 

<img width="223" alt="image" src="https://github.com/phetsims/mean-share-and-balance/assets/42476338/47535e77-cc28-4fa3-bebd-56ca929f58c0">
<img width="199" alt="image" src="https://github.com/phetsims/mean-share-and-balance/assets/42476338/112355cf-9e2e-4ad7-84be-de8ab6d708c8">

It seems a bit odd, and we probably want to address that.

**Comment by marlitas** [comment]
![image](https://github.com/phetsims/mean-share-and-balance/assets/42476338/a0338a5b-31f6-47df-a36a-6d1dddcd739e)
The line is also extending too far.

**Comment by marlitas** [comment]
As I was trying to polish this it became clear that the current cup layout logic was going to be difficult to maintain since it was different than the layout logic for the other screens. I went ahead and refactored the cups to have an xPositionProperty that does the layout logic for them. The margins for the predict mean line are now consistent between both screens and this will be easier to maintain in the future. 

This would benefit from a code review from @jbphet.

**Comment by jbphet** [comment]
As the first step in reviewing this I checked the behavior and noticed that the pencil is still protruding a little bit outside the bounds of the notepad.  Have we decided that this is okay?  It seems fine to me, but thought I should check.  The other (left) side of the line looks fine.  Screenshots:

![image](https://github.com/phetsims/mean-share-and-balance/assets/3082831/e2165e3a-27eb-42ed-9f99-bbe5df0144e1)

![image](https://github.com/phetsims/mean-share-and-balance/assets/3082831/f611ed1e-f2b9-41f6-b9fb-ce6ee9a89a71)

The code changes look good - they seem mostly to consist of changing from a 2D to a 1D position value for the cups, which seems like a good improvement.

Assigning back to @marlitas to respond to the question above.  If the current behavior is intentional and what we're after, this can be closed.

**Comment by amanda-phet** [comment]
It used to stick out fully on the Distribute screen, but I'm not sure what was really better. My only concern with the pencil sticking out is the case where you have the info dialog over it: 

![image](https://github.com/phetsims/mean-share-and-balance/assets/7852916/e26faa98-505f-4c11-9c81-2dbf7b551522)

In this case, I can still grab the pencil and move it. (I also noticed that I can tab to it even when it's not sticking out, so I'll add that to the relevant issue).

**Comment by marlitas** [comment]
Let's look at the position of the pencil synchronously. I'll mark it with the meeting: design label.

**Comment by marlitas** [comment]
We met with @amanda-phet and found a margin and notepad width that works for us. Ready to close!
