### ISSUE TITLE
Address phet-io state for distribution modes in Fair Share

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#226]
Since observable array listeners are now deferred we can wrap up phet-io state handling for Fair Share.

**Comment by marlitas** [comment]
This is done and ready for code review. Over to @jbphet!

**Comment by jbphet** [comment]
This all looks good to me.  I did make some changes, though, as I was doing the review.  Most were pretty minor, but I ended up changing the term "notepad mode" to "distribution mode" since it seems more specific and therefore potentially easier for maintainers and phet-io users to understand (which I believe @marlitas and I discussed a while back).  I also regenerated the phet-io API file to pick up these changes, but a lot of other things appeared to be changed in that file when this was done.  Given these relatively minor but non-trivial changes, I thought I should pass this back to @marlitas for one last look to make sure she's cool with what I've done.

**Comment by marlitas** [comment]
The changes look good. Thanks @jbphet. Closing.
