### ISSUE TITLE
Do we actually want to use Dialog for the Mean Info?

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#230]
While working on a comment from https://github.com/phetsims/mean-share-and-balance/issues/196, I discovered that 1 year ago Marla had implemented the Dialog API incorrectly. This is why we can see strange things in the studio tree where the dialog has both a `visibleProperty` and `isShowingProperty`:
<img width="228" alt="image" src="https://github.com/phetsims/mean-share-and-balance/assets/42476338/8357a591-8223-48fa-9988-0396d558cffb">

It is not an expected part of Dialog's API to use a `visibleProperty` to toggle on and off the appearance of the dialog. 

This incorrect implementation allowed us to do things that are not normally part of dialog UX. For example normally when a dialog pops up in our sims, the background darkens, and as soon as you click anywhere outside of the dialog the dialog immediately goes away.

Dialog Implementation:
<img width="767" alt="image" src="https://github.com/phetsims/mean-share-and-balance/assets/42476338/39ffb70b-437b-422e-babf-bd32bd0ec258">

Current Implementation:
<img width="768" alt="image" src="https://github.com/phetsims/mean-share-and-balance/assets/42476338/7bcabb3b-9acb-41da-8178-a32cb5d3734f">

This discovery is unfortunate because @amanda-phet pointed out that during interviews a student was exploring moving the balls around while seeing the calculations change in real time. 

In the end this is a design decision. We can keep the current behavior we have, and I move away from using a Dialog and instead it will act as a Node that is in front of everything in the notepad, or we use the Dialog API as is intended, and lose some of the current behavior, but remain more consistent with PhET dialog UX.

This should be discussed synchronously to avoid confusion.

**Comment by amanda-phet** [comment]
Design team wants this to be a non-modal dialog! Or at least a non-modal viewable thing. 

Questions: 
* Why do we only have modal dialogs? After all this time, is there a good reason for avoiding non-modal dialogs? Why isn't there currently a common code option to make non-modal dialogs? 
* In theory we could switch the "mode" or "view" of the notepad to show the mean calculation, using a toggle, instead of a dialog on top of the notepad. Should we do this? Pedagogically, we don't want to elevate this information to be more visible, so probably not. 
* Should we run this by others to get more thoughts into this implementation? 
* Can we just implement this as a node, and not worry about it looking like a non-modal dialog but not being called a dialog? 

@zepumph will take it from here.

**Comment by zepumph** [comment]
I created https://github.com/phetsims/sun/issues/882 and will report back with a recommendation on how to proceed in this sim.

**Comment by zepumph** [comment]
Today during Dev meeting, it was recommended that we just use a non `Dialog` node with a close button for this case. The common issue was closed and we can proceed with a custom Node for this context. Thanks!

**Comment by marlitas** [comment]
This is ready for review by @jbphet.

**Comment by jbphet** [comment]
Nice.  Changes look good, and it seems like a significant improvement.  Closing.
