### ISSUE TITLE
Add a success sound for mean prediction on screens 1 & 2

### ISSUE THREAD

**Issue by jbphet** [phetsims/mean-share-and-balance#235]
In https://github.com/phetsims/mean-share-and-balance/issues/233, the following question was raised:

> Should we have a success sound on the Level Out and Distribute screens if the stacks are leveled close to the prediction line? Similar to Balance Point?

In today's sound design meeting it was decided that yes, this should be added.  I'm logging a separate issue for it.

**Comment by jbphet** [comment]
@amanda-phet - I've implemented this behavior based on my current understanding of what we're after.  I included the entire highlight range on the predication line for the threshold where the sound gets activated, as you and I discussed over Slack.  

This is meant to be an initial stab at it that we can use for discussion and refinement.  Please let us know what you think.

**Comment by jbphet** [comment]
Also assigning to @Ashton-Morris in case he has any input.

**Comment by Ashton-Morris** [comment]
I think it sounds good, and works as desired!

**Comment by amanda-phet** [comment]
I think it's working great on Distribute, but not so great on Level Out. 

Not sure what to do... but I'm leaning toward not using this on Level Out. Is that a weird user experience? It's just really not pleasant with the water leveling sound, especially when the water levels are close to each other, but really in all scenarios I find it unpleasant. 

Rather than try to make it work, I'm thinking we don't use it on Level Out.

**Comment by jbphet** [comment]
@amanda-phet and I just discussed this over Zoom and tried reducing the volume of the leveling out sound so that it felt less like the two sounds were competing, and it seemed a bit better to both of us, so I've committed that change.

**Comment by amanda-phet** [comment]
I think this is much better. Thanks!
