### ISSUE TITLE
Make the pipes not interactive (enabledProperty)

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#243]
Just make meanShareAndBalance.levelOutScreen.view.controls.pipeSwitch.toggleSwitch.enabledProperty control the interactive valves at the same time

**Comment by marlitas** [comment]
Done above. Over to @amanda-phet and @jbphet for review.

**Comment by amanda-phet** [comment]
I'm a bit confused. 

`meanShareAndBalance.levelOutScreen.model.arePipesEnabledProperty` is working to control whether pipes are enabled by clicking the valve directly or the toggle. 

`meanShareAndBalance.levelOutScreen.view.controls.pipeSwitch.toggleSwitch.enabledProperty` only controls the toggle switch. 

Is this OK? It doesn't match what you wrote above, but we still achieved the goal of being able to disable all pipes in one location.

**Comment by amanda-phet** [comment]
Got it. Just wanted to be sure all was working as we want it to.

**Comment by jbphet** [comment]
This mostly looks good.  The only question I have is why the model was changed to use names like `pipesOpenProperty` instead of `arePipesOpenProperty`, but several of the objects to which these Properties are passed are using the older `arePipesOpenProperty` name.  If this wasn't by design, it would be good to use the newer, shorter name in all places, since it would make the code easier to understand.  If it *is* intentional, it would be good to have some documentation to explain why.

**Comment by marlitas** [comment]
Oh good catch! That's left over from changes in https://github.com/phetsims/mean-share-and-balance/issues/256. I'll go ahead and address.

**Comment by marlitas** [comment]
I updated the names mentioned above. I believe this issue is ready to close.
