### ISSUE TITLE
Instrument tick mark visibility on soccer field

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#253]
Ideally we want to pass this through as an option so it doesn’t impact CaV.

**Comment by marlitas** [comment]
I did this through an option in `SoccerScreenView`. Not sure if it's the best implementation so would definitely like to double check with @jbphet. Confirmed that it did not change the PhET-iO API for `center-and-variability`. 

Over to @amanda-phet for design review as well.

**Comment by jbphet** [comment]
@marlitas - I have a question about this: If it were not a goal to avoid impacting center-and-variability, would you still have created the `numberLineNodeTandem` option in `SoccerScreenView`?  I'm asking because this approach of passing through a tandem for something that is a subcomponent of the view feels very unusual and a bit ungainly to me.  I think if I saw it without knowing the history I would wonder why `SoccerScreenView` didn't just always create a sub-tandem for `playAreaNumberLineNode`.

If the answer is 'no', I would suggest using the simpler approach in the code and biting the bullet and dealing with the change to the CaV API.  It's a new phet-io item, so I don't think it would require a migration rule, or at least not much of one.

If the answer is `yes`, let's discuss a bit further so that I can better understand why.

**Comment by marlitas** [comment]
> If it were not a goal to avoid impacting center-and-variability, would you still have created the numberLineNodeTandem option in SoccerScreenView?

I would not have passed through the tandem in that wonky way otherwise, you are correct. The goal was to not impact CaV, but you're totally right adding a new phet-io item adds onto the API but doesn't create any migration issues that would need a rule. I'll go ahead and go the simpler route.

**Comment by marlitas** [comment]
Done above. I believe this can be closed if all looks good @amanda-phet

**Comment by amanda-phet** [comment]
This is working great!
