### ISSUE TITLE
Limit interactive area to the pencil

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/mean-share-and-balance#277]
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
Safari 17.5

**Problem description**
For https://github.com/phetsims/qa/issues/1094, @marlitas can you limit interaction to just the pencil instead of the entire prediction line?

A few times while trying to move a candy bar, I ended up moving the prediction line instead. 
@amanda-phet stated she had similar issues (see [comment](https://github.com/phetsims/qa/issues/1094#issuecomment-2161503272 )) 

Amanda and I only move the prediction line with the pencil. She also noted that in interviews, the users only used the pencil.

**Comment by marlitas** [comment]
I think this is a question for @amanda-phet. I know it's come up in the past, but we haven't changed it (pan & zoom came up once). We definitely can change it if we'd like though. @amanda-phet let me know what you want to do.

**Comment by amanda-phet** [comment]
Yes, sorry, we already talked about it. I'd like to move ahead with this and will change the labels.

**Comment by marlitas** [comment]
This has been addressed above. It changed the studio tree a bit, @amanda-phet and I talked about that and she was good with the changes. This is ready for @amanda-phet review and @jbphet code review.

**Comment by jbphet** [comment]
Reviewed, and I have a couple of quick comments:

1. The header comment in `MeanPredictionLine` seems out of date
2. The term "slider" is mentioned in a `MeanPredictionLine` when it talks about the sound, and it made me think that the sound generation should probably be moved to the handle (which *is* a slider) since it is meant to sound like a pencil on paper.
3. I made a few minor format changes that don't affect the functionality.  I don't think they would be controversial, but please have a look and make sure you're cool with them.

After these have been addressed I think it would be fine to close this.

**Comment by marlitas** [comment]
The formatting changes look good and I applied the above recommendations. Ready to close!
