### ISSUE TITLE
Potentially factor out constants

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/mean-share-and-balance#291]
Noting a couple of values that I see in multiple places, it may be better to move some of these to a cosntants file.

- ` fontSize: 15,` appears in a few places, what do you think about moving this to MeanShareAndBalanceConstants?
- Each Screen has the same options for ScreenIcon, what do you think about moving these to constants?

For #270.

**Comment by marlitas** [comment]
This was a lovely way to pixel polish some of the text throughout the sim because I noticed that some text was using size 15 instead of 16, and the distribution button text was also smaller than it appears to be in the design doc. @amanda-phet you should review to make sure the font sizes look as expected, or if me unifying things a bit threw something off in a way.

Other than that I consolidated constants and I think this can be closed if the font sizes look good!

**Comment by amanda-phet** [comment]
Looks good to me!
