### ISSUE TITLE
Move IOType implementation to core type

### ISSUE THREAD

**Issue by marlitas** [phetsims/mean-share-and-balance#306]
From slack @pixelzoom said: " In general, put as much of the implementation as possible in the core type, and keep the IOType light."
So `setDataPoints` and the like should call a method that is defined in the core type.

I also need to update the IOs to be private static readonly members of the core class type. This needs to be done in BalancePointModelIO, SharingModelIO, and LevelOutModelIO.

**Comment by marlitas** [comment]
Done above. Over to @jbphet for review.

**Comment by jbphet** [comment]
The general idea of moving the functionality from the IOType to the core type makes a lot of sense, and the code changes look reasonable to me.

@marlitas - Note that I changed the following constant...

```js
public static readonly numberOfKicksRangeProperty = NUMBER_OF_KICKS_RANGE_PROPERTY;
```

...to...

```js
public static readonly NUMBER_OF_KICKS_RANGE_PROPERTY= NUMBER_OF_KICKS_RANGE_PROPERTY;
```

While I was doing this, since I think this is more in keeping with our coding conventions.

Other than that, all looks good.  Closing.
