### ISSUE TITLE
Sim freezes when jumping to min/max with 'Share' selected

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/mean-share-and-balance#312]
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
Safari 17.5

**Problem description**
For https://github.com/phetsims/qa/issues/1105, on the Fair Share Screen, pressing hotkeys for min/max while 'Share' is selected causes incorrect images on the notepad, the people to shift to the right, and the sim to freeze. 

**Steps to reproduce**
1. On the Fair Share Screen, press the Share button with mouse or keyboard
2. Tab to the controls for Number of People
3. Use home/end keys to jump to max and then to min

**Visuals**
<img width="1338" alt="Screenshot 2024-07-09 at 8 25 15 AM" src="https://github.com/phetsims/mean-share-and-balance/assets/87318828/5caafaf9-3310-4e41-ac3f-8b7d163a22d3">

<img width="497" alt="Screenshot 2024-07-09 at 7 58 25 AM" src="https://github.com/phetsims/mean-share-and-balance/assets/87318828/480f3a16-fcef-4e09-810d-9022504e41a9">
<img width="497" alt="Screenshot 2024-07-09 at 7 58 43 AM" src="https://github.com/phetsims/mean-share-and-balance/assets/87318828/d53ab3fc-025f-4818-b873-981ccad6132c">

<Details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Mean: Share and Balance‬
URL: https://phet-dev.colorado.edu/html/mean-share-and-balance/1.1.0-dev.7/phet/mean-share-and-balance_all_phet.html
Version: 1.1.0-dev.7 2024-07-08 22:39:22 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15
Language: en-US
Window: 1354x678
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by jbphet** [comment]
Nice bug @Nancy-Salpepi!

This issue was rooted in the code's inability to handle a change to the number of plates that is greater than 1.  The change to the number of plates was driving changes to the `isActiveProperty` for each of the plates one by one, and these changes to `isActiveProperty` were causing updates to the number of apples per plate (since the screen was in "Share" mode).  The calculation for the number of items to add to a plate was off because part of the state information indicated that there were still a lot of apples around, while another part indicated that there was only one plate left, and it resulted in a whole lot of apples being added to one plate.  Hence the big stack of apples in the screen capture above.

@marlitas and I talked through some solutions, and decided to base the number of snacks to add to a plate on the current number of plates, since that is a more "foundational" property in the sense that it drives some of the other values.  This seems to work, and has been committed.

Assigning to @marlitas for review.

**Comment by marlitas** [comment]
@jbphet and I discussed this as a solution earlier and I agree the implementation looks good. I went ahead and looked at it in the state wrapper as well and saw nothing suspicious.

I'll send it over to @Nancy-Salpepi to confirm it looks good on main. Feel free to close.

**Comment by Nancy-Salpepi** [comment]
Working great on main! Closing.
