### ISSUE TITLE
Reset Sim when changing Region and Culture Preference

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/mean-share-and-balance#316]
For https://github.com/phetsims/qa/issues/1105, it was decided that the behavior across screens should be consistent when changing the Region and Culture preference. Currently the sim resets only on the Balance Point Screen, but @amanda-phet would like this behavior across along screens.

**Comment by marlitas** [comment]
@amanda-phet and I talked this through and decided not to reset in the other screens. The reason being that we actually aren't doing a full screen reset in Balance Point. We are only resetting the balls and kickers. This was done in center and variability (and therefore soccer-common) because it felt odd to have one kicker out and then when you change the region a completely different kicker appears.

We also noticed that no other sims are resetting on a region and culture change.

Closing as a won't fix.
