### ISSUE TITLE
Screenshots not rendering lines correctly?

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/mean-share-and-balance#325]
While working on https://github.com/phetsims/mean-share-and-balance/issues/205

I noticed that the PhET screenshot tool was making the pencil marks look like thick black lines. This was using chrome on a mac. 

![Mean_ Share and Balance screenshot (1)](https://github.com/user-attachments/assets/fb2335ea-442a-4f84-9261-086d7f790fdb)
![Mean_ Share and Balance screenshot (2)](https://github.com/user-attachments/assets/744ea7c1-42c5-4653-b75b-ddca465cd7db)

Is this a known issue? Maybe something we won't fix?

**Comment by amanda-phet** [comment]
I took a screenshot using the chrome dev tools and didn't have the issue, which is good for #205 
![phet-dev colorado edu_html_mean-share-and-balance_1 1 0-dev 7_phet_mean-share-and-balance_all_phet html (1)](https://github.com/user-attachments/assets/1e4ed4d9-fa4b-4f1d-8b6c-9e782ddadd14)

**Comment by marlitas** [comment]
@jonathanolson the pencil marks @amanda-phet is talking about are using `Pattern`. I tried looking for an issue but couldn't find one. Not sure if this is known or I should create something in scenery. Either way it doesn't seem blocking to me, but I'm probably not the one to make that final call.

**Comment by marlitas** [comment]
Talked through this with @jonathanolson and it was a matter of how I factored out the pattern to the constants file. Essentially, the sim doesn't pre-load the image files when they are in a module (like the constants file), therefore the images need to be added in in the sim classes themselves. Because these images are SVG the html handle the loading of that differently, but screenshots are rendered using canvas which does not allow for the preload to happen. I will go through and fix this instances. Thanks!

**Comment by marlitas** [comment]
I fixed this above. @amanda-phet this is ready for your review.

**Comment by amanda-phet** [comment]
Screenshots look great!
