### ISSUE TITLE
Able to move balls with alt input when enabledProperty=false

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/mean-share-and-balance#337]
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1121, in Studio on the Balance Point screen, setting the enabledProperty to false for the soccer balls still allows them to be moved with alt input.

**Steps to reproduce**
1. In studio set the enabledProperty for all the soccer balls to false.
2. Kick the balls
3. Tab to the balls, grab a ball, and use arrow keys move it

**Visuals**

https://github.com/user-attachments/assets/9d14a569-b36f-4b1c-b92a-2a77d5231068

**Comment by marlitas** [comment]
Hmmm there should be no cueing indicators either. Oh I see you just opened an issue for that as well.

**Comment by Nancy-Salpepi** [comment]
I didn't realize there was this property: soccerBallsEnabledProperty 
That property works correctly.

The bug I saw was when I set the enabledProperty of each ball to false.

**Comment by marlitas** [comment]
I fixed the alt-input situation with this, but there still are some oddities I'm not quite sure how we want to handle. For example, if I disable input for all of the top soccer balls, but some of the bottom ones are still enabled I still get the mouse cue. 

<img width="771" alt="image" src="https://github.com/user-attachments/assets/b4489a56-8d6f-4a7a-ace8-bb8b40262ad0">

The visibility of the mouse cue right now is only tied to wether the `soccerBallsEnabledProperty` is true/false, not the individual enabledProperties. Personally, this feels documentation worthy in examples.md. I can toggle the visibility of the mouse cue based on whether all top balls are enabled or not, but it feels unnecessary to complicate the code when we already have a wonderful Property to help clients with these. I don't think it's worth it to provide two ways of doing the same thing.

Thoughts? 

Also important to note, the studio tree has now changed a bit since I needed to access the `enabledProperty` in the model. You can now toggle the `enabledProperty` for each soccer ball either under `model.sceneModel.soccerBalls.soccerBall*.enabledProperty` or as a linked Property in `view.sceneView.soccerBallNodes.soccerBallNode*.enabledProperty`

Over to @amanda-phet to weigh in on the above question and review the final behavior.

**Comment by amanda-phet** [comment]
It's a little funky... For example, I set `meanShareAndBalance.levelOutScreen.model.initialWaterLevelsProperty` and the cups didn't come out how I set them, but I clicked reset and Set Value a few times and eventually things worked out. I think if  I was more methodical I could figure out the sequence, but my overall question is just if clicking 'Set Value' should immediately set the value of all 7 cups, which I think it should, and that's not happening. 

It seems to be working well on the Distribute and Faire Share screens!

**Comment by catherinecarter** [comment]
Upon testing CaV, we found two situations, one where the hand appears on the number line with potentially no ball at that tick mark, and one where the hand appears in the upper left.

**Situation 1 -- hand appears on number line based on previous situation**
1. Kick the max number of balls (at least one needs to be enabled so the hand appears)
2. Hit the orange reset all button
3. Disable each ball individually
4. Kick the max again
5. The cueing hand often appears in strange locations based on some previous situation, shown below:
![image](https://github.com/user-attachments/assets/39d99dfa-7a23-43c1-b41b-62a17c5068e5)

**Situation 2 -- hand appears in upper left corner**
1. Reload sim so it thinks no balls have ever been kicked
2. Follow only steps from above 3, 4, 5, in order.
![image](https://github.com/user-attachments/assets/fd1c29dd-24e1-4bab-80f8-18ca519d4d05)

**Comment by amanda-phet** [comment]
I'm going to update examples.md to say two things: 
1. If you want all balls disabled, don't do them individually. Use `meanShareAndBalance.balancePointScreen.model.soccerArea.soccerBallsEnabledProperty`
2. If you disable some balls, the cueing arrow may end up in unpredictable locations, so we don't recommend doing that.

**Comment by marlitas** [comment]
I committed a fix that handles the above scenarios more cleanly than it had been. I think the warnings that @amanda-phet wants to put in examples.md are still warranted, but hopefully we avoid as many of the ultra-buggy scenarios as possible. I think this is ready for cherry-pick for QA to verify and test. 

QA: It will be important to check that keyboard input/cues have not regressed with the soccer ball interactions. Especially in conjunction with PhET-iO.

**Comment by Nancy-Salpepi** [comment]
@amanda-phet @marlitas Since it isn't recommended to set the enabledProperty to false for the individual soccer balls, maybe those elements shouldn't be featured?

**Comment by Nancy-Salpepi** [comment]
Ah gotcha! Thanks for explaining CC!

**Comment by KatieWoe** [comment]
I get this console error, and a pop up error, when the keyboard focus is on a disabled soccer ball and you press an arrow key.
![consolesoccer](https://github.com/user-attachments/assets/85dca9f5-62c1-4544-b87d-1af4a8fb15b6)

**Comment by Nancy-Salpepi** [comment]
Noting that the error appears when `meanShareAndBalance.balancePointScreen.model.soccerArea.soccerBallsEnabledProperty` is false. 
When the `enabledProperty` of an individual ball is false, it isn't possible to focus on that ball.

**Comment by marlitas** [comment]
I discussed enabled/disabled behavior on keyboard with @zepumph. He let me know that we do indeed want to be able to "select" disabled items so that users can get screen reader information from them, but we do not want to be able to "sort" disabled items. We added an option to GroupSortInteractionView that gives more flexibility on how sims can handle individual item enabled state alongside the larger group disabled state. 

This should now be a smoother experience overall for keyboard users. 

@amanda-phet and @catherinecarter the mouse cue may still appear on a disabled ball. There is little more I can do to handle that situation without further complicating the code to a point that I do not believe is worth it. Let me know if this causes any concerns.

Assigning to @zepumph for review.

**Comment by zepumph** [comment]
Looks great. I agree that the cue logic is not very kind to adding the notion of individual group item enables. Would you mind creating an issue in scenery-phet just so we can track that. I bet QA will find that before we are done. 

https://github.com/phetsims/scenery-phet/blob/5fa5a3130c9cd81f2323cf22ff0f8ef2b6469d97/js/accessibility/group-sort/model/GroupSortInteractionModel.ts#L180-L187

**Comment by marlitas** [comment]
@zepumph I'm hesitant to create that issue because I don't really think it should be supported? If clients are disabling all individual items in a groupSort they should be doing that with the general enabledProperty for the groupSort interaction in general.

**Comment by amanda-phet** [comment]
That all sounds fine to me, @marlitas .

**Comment by marlitas** [comment]
Okay. I'll create the issue. But definitely doesn't need to be handled for MSaB.

**Comment by catherinecarter** [comment]
Seems reasonable to note this behavior in examples.md and keep the logic as it is currently (behavior with the cueing hand on disabled balls). 

My only real concern is in the situation shown below. Since none of the balls are enabled (which the user shouldn't be doing, per examples.md), the hand appears, but there's no way to remove it since I can't tell the sim that I have recognized the cue and acted on it. Maybe this should added to examples as a consequence of disabling each ball rather than the group? What do you think, @amanda-phet?

![image](https://github.com/user-attachments/assets/66b45108-16f6-4844-9a80-6f4ae18a9a12)

**Comment by amanda-phet** [comment]
Made a slight tweak to examples.md with @catherinecarter that can be used for both MSaB and CaV. I think we are done here!

**Comment by Nancy-Salpepi** [comment]
Addition to the examples.md looks good. 

I do see this one oddity....when disabling some of the kicked balls, if I disable the last ball kicked, in the Standard PhET-iO wrapper, when I grab a ball, the cueing hand/arrows will briefly move to the last ball kicked before disappearing. 


https://github.com/user-attachments/assets/8a25addf-8f85-449c-b74e-56502576cf95

**Comment by KatieWoe** [comment]
Found a more general version of https://github.com/phetsims/mean-share-and-balance/issues/337#issuecomment-2302411636
https://github.com/phetsims/mean-share-and-balance/issues/350

**Comment by marlitas** [comment]
I believe https://github.com/phetsims/mean-share-and-balance/issues/337#issuecomment-2302411636 was fixed by the commit in https://github.com/phetsims/mean-share-and-balance/issues/350

**Comment by Nancy-Salpepi** [comment]
This looks fixed in rc.4.
Closing.
