### ISSUE TITLE
Disabling interaction on singular soccer balls is odd when balls are stacked

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/mean-share-and-balance#344]
**Device**
Samsung Laptop
**OS**
Win 11
**Browser**
Firefox
**Problem Description**
For https://github.com/phetsims/qa/issues/1134. Seens when exploring https://github.com/phetsims/mean-share-and-balance/issues/337.
When you use the ctrl/alt shortcuts in studio to look at individual soccerballs, only alt(view) works, ctrl only takes you to view, not to model. If the balls are stacked, you can only use the shortcuts to look at the soccerball on the top of the stack, but only by having your cursor on a lower ball. If a ball on the top of a stack is disabled, you can't use keyboard nav to focus on or move the lower balls.
**Visuals**
![ballfocus](https://github.com/user-attachments/assets/6f7b2f55-a6c4-43e9-8835-1e61df30d920)

**Comment by jbphet** [comment]
With help from @zepumph, the first portion of the reported problem has been addressed, so now ctrl-hover will go to the phet-io ID for the soccer ball model elements and not the view nodes.

As for the other reported problem - where the bottom balls on a stack can't be reference via alt-hover or ctrl-hover - @zepumph and I looked at this for a while and decided to recommend that we live with this behavior.  The problem is due to the fact that the pointer areas for the top balls on the stack are extended to cover the whole stack so that users can't grab balls within the stack (see screenshot below).  We could potentially work around this through some sort of scheme where the hit test checks for balls that are lower in the stack and whether those are actually the intended target for phet-io interactions, but the code would be quite complex.  This use case seems rare, and the problem is easy to work around, so the additional complexity and time to address doesn't seem worth it in my opinion.

![image](https://github.com/user-attachments/assets/cb0a1979-52d7-42a3-9fbd-e21af69111e3)

Assigning to @marlitas to review the change and to see if she concurs with the recommendation.

**Comment by marlitas** [comment]
I agree, it is not worth investigating that hover behavior for the stacked balls. Tagging @amanda-phet and @catherinecarter so that they are both aware. 

I looked at the change and tested the behavior I believe this is ready for cherry-pick. Thanks!

**Comment by amanda-phet** [comment]
I agree. Thanks for letting us know!

**Comment by KatieWoe** [comment]
Ctrl still selects the top ball only, even if hovering over lower balls, but you can hover over the top ball as well now. Is this the intended behavior?

**Comment by marlitas** [comment]
@KatieWoe, yes! That is the intended behavior.

**Comment by KatieWoe** [comment]
Closing then
