### ISSUE TITLE
More GroupSortInteraction + Mouse multi-input bugs

### ISSUE THREAD

**Issue by zepumph** [phetsims/mean-share-and-balance#352]
From https://github.com/phetsims/mean-share-and-balance/issues/329#issuecomment-2297731877 we know there is consistent behavior in the sim when using GroupSortInteraction and mouse at the same time. This was brought up at dev meeting today and through just a bit of testing I could cause assertion errors and buggy interaction state easily. 

For example:
* On screen two
* Tab to group selection and get the top left candy bar
* Click and drag that one away with the mouse
* click tab to highlight the currently dragging bar, and press space to grab it
* Press left arrow key and an assertion triggers.

I believe it would be a reasonable fix/workaround to add in an interrupt step such that if you begin a mouse drag, you interrupt the group sort, and if you focus the group sort, you interrupt each bar dragListener. It may even be easy to do.

We may find that something like this is necessary on a sim specific level even if we make progress more generally over in https://github.com/phetsims/joist/issues/750.

Does this kind of assertion that causes a buggy interaction in production block MSaB?

**Comment by zepumph** [comment]
After the above commit that adds interrupt, the below patch works pretty well to cancel out the "dual input fighting" behavior that was causing trouble.

```diff
Subject: [PATCH] always build the allHTML, https://github.com/phetsims/chipper/issues/1454
---
Index: js/distribute/view/NotepadCandyBarNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/distribute/view/NotepadCandyBarNode.ts b/js/distribute/view/NotepadCandyBarNode.ts
--- a/js/distribute/view/NotepadCandyBarNode.ts	(revision a975ea5a43d0cbff65d44727938e319cb9e4d6ab)
+++ b/js/distribute/view/NotepadCandyBarNode.ts	(date 1724353659231)
@@ -106,6 +106,7 @@
 
         // When the candy bar is grabbed with the mouse, set the mouseSortedGroupItem property to true.
         groupSortInteractionModel.setMouseSortedGroupItem( true );
+        groupSortInteractionModel.interrupt();
         candyBar.draggingProperty.value = true;
         this.moveToFront();
       },
@@ -118,6 +119,8 @@
 
     this.addInputListener( this.dragListener );
 
+    groupSortInteractionModel.isKeyboardFocusedProperty.lazyLink( isKeyboardFocused => isKeyboardFocused && this.dragListener.interrupt() );
+
     this.candyBar.positionProperty.link( position =>
       this.setTranslation( modelViewTransform.modelToViewPosition( position ) )
     );


```


There is still an easy assertion that can trigger, since when a candy bar is animated back onto the stack on top of the current group sort selection, then it isn't recomputed, but that can be likely fixed wherever you are updating the selection to begin with (just upon the animation start/completion or something).

@jbphet, let me know what you think.

**Comment by jbphet** [comment]
I tried the sequence described above on MSaB RC.4, and it didn't crash the sim or get it into a particularly weird state.  It was a little odd, but nothing major.  So while an assertion is thrown when assertions are on, this is unlikely to cause any significant problems for our users.

**Comment by jbphet** [comment]
I've applied the patch on main, and it improves the situation somewhat, but it is still pretty easy to hit an assertion with these interactions.  Here's the sequence from above with a couple of additional steps, and if this is done on the sim with the patch applied, we hit an assertion that says, "the selected candy bar should be the top one" at the end:

1. Go to screen two
2. Tab to group selection and grab the top left candy bar
3. Click and drag that one away with the mouse
4. Press the Tab key once (this will move focus to one of the plate number controls)
5. Press shift-Tab to re-select the candy bar group
6. Press Space to select the candy bar
7. Press the left arrow

I talked with @zepumph about this situation, and he said that he still feels like the patch is a significant improvement, since it interrupts interactions between group sort and pointer dragging.  I'm okay to apply it, but I'd like to take a little bit of time to see if I can improve the behavior in the scenario just above too.

**Comment by jbphet** [comment]
By changing the code that updates the selected group item to consider snacks that are in the process of animating to a plate, we can fix the problem where a candy bar below the top one ends up being selected, which corrects the problem described in the previous comment.

**Comment by KatieWoe** [comment]
![image](https://github.com/user-attachments/assets/54675300-46b4-48bd-8264-8b6bd058d948)
I was able to get this situation occasionally. It did not cause any assertions. I could not get it consistently, but steps seem to include:
1. On the soccer screen, kick all the balls
2. Pick one up with mouse interaction and hold it
3. Use keyboard nav to select the currently held soccer ball
4. Press space to pick it up while dragging the ball with mouse
5. The cue arrows will stay behind.

**Comment by zepumph** [comment]
Thanks for the report! In my mind, we probably don't want to try to handle every single buggy case between keyboard/mouse. The work in this issue provided a baseline interrupt, which I think is the main win for this. So long as the above case doesn't break the sim or input, I wouldn't probably try to spend this time so late in RC (where a fix could likely cause a more serious regression than the original bug we are fixing). 

In the end it is up to @jbphet and @marlitas and designers how to proceed. I support you!

**Comment by jbphet** [comment]
The development team has been discussion the interaction between keyboard navigation and mouse (pointer) interaction in our developer meetings, and @jessegreenberg is going to look into making some general improvements.  Hopefully that will help situations like this.

As for the specific issue that @KatieWoe [noted above](https://github.com/phetsims/mean-share-and-balance/issues/352#issuecomment-2310687377), I'm able to duplicate it somewhat, and it doesn't seem like something our users are likely to run into and it wouldn't cause much of a problem if they did, so I'm going to say that this is a non-blocking issue and proceed with publication.  I think I'll also just close this, since it's unlikely that we'll decide to allocate resources to fix it.
