### ISSUE TITLE
Replace "Auto Share" checkbox with push buttons.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/mean-share-and-balance#61]
For code review #41...

After playing with this sim for close to 4 hours, I finally figured out the "Auto Share" checkbox.  When you check it, it opens all pipes.  If you close any pipe, it unchecks the checkbox (which is in general rude and confusing for a checkbox).   And the only way I figured it out was by stumbling across a code comment (at instantiation, not at declaration) that explained it. 

In addition to not understanding what "Auto Share" means, and being concerned that users will not understand it either...  A checkbox is absolutely the wrong UI component for this feature.  It should be a push button that moves all pipes to the open position.   Eliminate the word "Auto Share" and use an icon showing the valve handle in the open position. 
 
Also assigning to design @amanda-phet.

**Comment by pixelzoom** [comment]
This is even more confusing than I thought.... If I uncheck the "Auto Share" checkbox myself (versus having it automatically unchecked by closing a valve) then all valves close.  So if I close one value myself, the only way I can close them all is to check then uncheck the box. Yikes. 

How about 2 push buttons, with appropriate icons? One to close all valves, one to open all values.

**Comment by amanda-phet** [comment]
In response to the issue about the name of this control, we are considering changing the name for this screen since there isn't really "sharing" on this screen like there will be on the Fair Share screen. We like something like "open all valves" and "close all valves" on two buttons, or keeping the checkbox behavior but calling it something else. 

Also considering removing this control, since it exists mostly out of convenience (whereas on the Fair Share screen, the control is necessary for what it controls). The user can manually share between cups and leave them in that state. 

@BLFiedler also added: 
>Having an external action change the state of a checkbox without direct user action is a little bit of an accessibility problem. Not sure if that is possible in this if you change an individual valve. 

Decision: let's get rid of this control on this screen!

**Comment by marlitas** [comment]
Auto-share removed. Closing
