### ISSUE TITLE
Manipulator on "Predict Mean" line is too small

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/mean-share-and-balance#64]
For code review #41 ...

The manipulator on the "Predict Mean" line is _so_ tiny. Why?

<img width="536" alt="screenshot_1723" src="https://user-images.githubusercontent.com/3046552/176314737-a779bb5b-ea77-420d-ab5a-ceadae956d71.png">

**Comment by marlitas** [comment]
Removing assignment until designer feedback on size of manipulator is received.

**Comment by amanda-phet** [comment]
We can make it larger! Is there a default size for this? Maybe we can try the size of the manipulators in the Number Line sims?

**Comment by marlitas** [comment]
I'll reference NumberLine sims for now, and see if that feels better.

**Comment by marlitas** [comment]
Seems disproportionately large now... but may be because I'm used to seeing it smaller. I do feel like the triangles on the 3D watercups should be made bigger if we like this size, so that the proportions feel a little more connected across both sets.
<img width="709" alt="Screen Shot 2022-07-14 at 5 00 42 PM" src="https://user-images.githubusercontent.com/42476338/179112940-a1a0772b-0279-4e9f-8073-2e9fa3da7ead.png">

Assigning to @amanda-phet for feedback.

**Comment by amanda-phet** [comment]
We reduced the size slightly and are all happy with the medium size.

**Comment by marlitas** [comment]
This has been addressed, reviewed, and approved in design meeting. Closing.
