### ISSUE TITLE
Reconsider UI for changing number of cups

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/mean-share-and-balance#66]
For code review #41 ...

Some feedback on this control:

<img width="161" alt="screenshot_1725" src="https://user-images.githubusercontent.com/3046552/176315477-502fc828-375b-411e-86aa-ee7d95bd481c.png">

(1) I really don't like left-right spinners. Up-down is a much better UX, especially when considering right-to-left languages.

(2) I don't like using text labels where we don't need to. 

So for this control...  I think a NumberPicker (not a NumberSpinner) with a cup icon to the right of it would accurately describe what the control does. And it would be a better UX.

**Comment by marlitas** [comment]
In this issue: https://github.com/phetsims/mean-share-and-balance/issues/25 @amanda-phet determined the left-right NumberSpinner was preferable. This sim started with a NumberPicker and did not provide the desired result as determined by designers and dev team according to spacing as well as functionality with future screens. 

Leaving issue open to address question of text label vs. icon. Removing assignment for designer feedback.

**Comment by amanda-phet** [comment]
Discussed 7/14/22 and would like to leave this control as-is. The text is helpful (e.g. if a teacher is discussing how to calculate the mean, they would say "divide by the total number of cups" or "devide by the number of cups"), and adding another cup to the screen could be too many cups. 

The discussion about the number control happened in a previous issue and meetings, and we prefer to use this control in this case because a vertical number picker will be confusing on a later screen.
